version: '2'
services:
  db:
    extends:
      file: docker-compose.common.yml
      service: db
  python:
    extends:
      file: docker-compose.common.yml
      service: python
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - "8000:8000"
  node:
    extends:
      file: docker-compose.common.yml
      service: node
    ports:
      - "3000:3000"
  nginx:
    image: nginx
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./22urlfront/static/:/var/www/front/
    ports:
      - "8001:8001"
      - "8002:8002"
    links:
      - node
      - python
