version: '2'
services:
  db:
    extends:
      file: docker-compose.common.yml
      service: db
  python:
    extends:
      file: docker-compose.common.yml
      service: python
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - "8000:8000"
  node:
    extends:
      file: docker-compose.common.yml
      service: node
    depends_on:
      - python
    ports:
      - "3000:3000"
    command: [sh, -c, yarn install && yarn run dev]
