version: '2'
services:
  db:
    image: postgres
  python:
    build: ./docker/python
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./djangoserver:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
  node:
    image: node:10.7.0
    volumes:
      - ./22urlfront:/src
      - .docker_node_modules:/src/node_modules
    working_dir: /src
    command: [sh, -c, yarn install && yarn run dev]
    ports:
      - "3000:3000"
  nginx:
    image: nginx
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8001:8001"
      - "8002:8002"
    links:
      - node
      - python
