version: '2'
services:
  db:
    image: postgres
    environment:
      PGDATA: /var/lib/pgsql/data/url
      POSTGRES_USER: "changeme"
      POSTGRES_PASSWORD: "changeme"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - "./db/data:/var/lib/pgsql/data/url"
  python:
    build: ./docker/python
    volumes:
      - ./djangoserver:/src
  node:
    image: node:11.15.0
    volumes:
      - ./front:/src
      - .docker_node_modules:/src/node_modules
    working_dir: /src
