version: '2'
services:
  db:
    extends:
      file: docker-compose.common.yml
      service: db   
    restart: always
  python:
    extends:
      file: docker-compose.common.yml
      service: python
    command: uwsgi --http :8000 --module djangoserver.wsgi
    restart: always
    depends_on:
      - db
    ports:
      - "127.0.0.1:8000:8000"
  node:
    extends:
      file: docker-compose.common.yml
      service: node
    command: [sh, -c, yarn install && yarn run build && yarn run start]
    ports:
      - "127.0.0.1:3000:3000"
